spring:
  application:
    name: ecommerce

  config:
    # Load .env locally (optional - will be skipped on Render where env vars are set directly)
    import: optional:file:backend/.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:false}

    
server:
  port: ${PORT:8080}